input {
    kb_layout = gb,br
    kb_options = grp:alt_caps_toggle
    sensitivity=0.4
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

#input {
#    kb_layout = gb,br
#    # follow_mouse = 1
#    sensitivity = 8
#    # force_no_accel = 0
#    # accel_profile = flat 
#    # numlock_by_default = true
#
#    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
#    touchpad {
#        natural_scroll = yes
#    }
#
#}
