-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.define_submap("global", function()

    -- ## Shell keybinds
    -- Launcher
    --bindi = Super, Super_L, global, caelestia:launcher
    hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("caelestia shell drawers toggle launcher"), { release = true })
    hl.bind(mainMod .. " + catchall", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse:272", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse:273", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse:274", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse:275", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse:276", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse:277", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse_up", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })
    hl.bind(mainMod .. " + mouse_down", hl.dsp.global("caelestia:launcherInterrupt"), { non_consuming = true, ignore_mods = true })

    -- Misc
    -- TODO: manual review on line 19 — no mapping for dispatcher "caelestia:session"
    -- hl.bind(kbSession .. " + global", hl.dsp.caelestia_session())
    -- TODO: manual review on line 20 — no mapping for dispatcher "caelestia:sidebar"
    -- hl.bind(kbShowSidebar .. " + global", hl.dsp.caelestia_sidebar())
    -- TODO: manual review on line 21 — no mapping for dispatcher "caelestia:clearNotifs"
    -- hl.bind(kbClearNotifs .. " + global", hl.dsp.caelestia_clearNotifs(), { locked = true })
    -- TODO: manual review on line 22 — no mapping for dispatcher "caelestia:showall"
    -- hl.bind(kbShowPanels .. " + global", hl.dsp.caelestia_showall())
    -- TODO: manual review on line 23 — no mapping for dispatcher "caelestia:lock"
    -- hl.bind(kbLock .. " + global", hl.dsp.caelestia_lock())
    hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("pgrep -x sunsetr && pkill sunsetr || sunsetr"))

    -- Restore lock
    -- TODO: manual review on line 27 — no mapping for dispatcher "caelestia shell -d"
    -- hl.bind(kbRestoreLock .. " + exec", hl.dsp.caelestia_shell__d(), { locked = true })
    -- TODO: manual review on line 28 — no mapping for dispatcher "caelestia:lock"
    -- hl.bind(kbRestoreLock .. " + global", hl.dsp.caelestia_lock(), { locked = true })

    -- Brightness
    hl.bind("XF86MonBrightnessUp", hl.dsp.global("caelestia:brightnessUp"), { locked = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.global("caelestia:brightnessDown"), { locked = true })
    --bindle = , XF86MonBrightnessUp, exec, brightnessctl set 10%+
    --bindle = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

    -- Media
    hl.bind("Ctrl+$mainMod + Space", hl.dsp.global("caelestia:mediaToggle"), { locked = true })
    hl.bind("XF86AudioPlay", hl.dsp.global("caelestia:mediaToggle"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.global("caelestia:mediaToggle"), { locked = true })
    hl.bind("Ctrl+$mainMod + Equal", hl.dsp.global("caelestia:mediaNext"), { locked = true })
    hl.bind("XF86AudioNext", hl.dsp.global("caelestia:mediaNext"), { locked = true })
    hl.bind("Ctrl+$mainMod + Minus", hl.dsp.global("caelestia:mediaPrev"), { locked = true })
    hl.bind("XF86AudioPrev", hl.dsp.global("caelestia:mediaPrev"), { locked = true })
    hl.bind("XF86AudioStop", hl.dsp.global("caelestia:mediaStop"), { locked = true })

    -- Kill/restart
    hl.bind("Ctrl+$mainMod+Shift + R", hl.dsp.exec_cmd("qs -c caelestia kill"), { release = true })
    hl.bind("Ctrl+$mainMod+Alt + R", hl.dsp.exec_cmd("qs -c caelestia kill; sleep .1; caelestia shell -d"), { release = true })

    -- Go to workspace #
end)

local wsaction = "~/.config/hypr/scripts/wsaction.fish"
hl.bind(kbGoToWs .. " + 1", hl.dsp.exec_cmd(wsaction .. " workspace 1"))
hl.bind(kbGoToWs .. " + 2", hl.dsp.exec_cmd(wsaction .. " workspace 2"))
hl.bind(kbGoToWs .. " + 3", hl.dsp.exec_cmd(wsaction .. " workspace 3"))
hl.bind(kbGoToWs .. " + 4", hl.dsp.exec_cmd(wsaction .. " workspace 4"))
hl.bind(kbGoToWs .. " + 5", hl.dsp.exec_cmd(wsaction .. " workspace 5"))
hl.bind(kbGoToWs .. " + 6", hl.dsp.exec_cmd(wsaction .. " workspace 6"))
hl.bind(kbGoToWs .. " + 7", hl.dsp.exec_cmd(wsaction .. " workspace 7"))
hl.bind(kbGoToWs .. " + 8", hl.dsp.exec_cmd(wsaction .. " workspace 8"))
hl.bind(kbGoToWs .. " + 9", hl.dsp.exec_cmd(wsaction .. " workspace 9"))
hl.bind(kbGoToWs .. " + 0", hl.dsp.exec_cmd(wsaction .. " workspace 10"))
-- Go to workspace group #
hl.bind(kbGoToWsGroup .. " + 1", hl.dsp.exec_cmd(wsaction .. " -g workspace 1"))
hl.bind(kbGoToWsGroup .. " + 2", hl.dsp.exec_cmd(wsaction .. " -g workspace 2"))
hl.bind(kbGoToWsGroup .. " + 3", hl.dsp.exec_cmd(wsaction .. " -g workspace 3"))
hl.bind(kbGoToWsGroup .. " + 4", hl.dsp.exec_cmd(wsaction .. " -g workspace 4"))
hl.bind(kbGoToWsGroup .. " + 5", hl.dsp.exec_cmd(wsaction .. " -g workspace 5"))
hl.bind(kbGoToWsGroup .. " + 6", hl.dsp.exec_cmd(wsaction .. " -g workspace 6"))
hl.bind(kbGoToWsGroup .. " + 7", hl.dsp.exec_cmd(wsaction .. " -g workspace 7"))
hl.bind(kbGoToWsGroup .. " + 8", hl.dsp.exec_cmd(wsaction .. " -g workspace 8"))
hl.bind(kbGoToWsGroup .. " + 9", hl.dsp.exec_cmd(wsaction .. " -g workspace 9"))
hl.bind(kbGoToWsGroup .. " + 0", hl.dsp.exec_cmd(wsaction .. " -g workspace 10"))
-- Go to workspace -1/+1
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = -1 }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "+1" }))
-- TODO: manual review on line 76 — no mapping for dispatcher "-1"
-- hl.bind(kbPrevWs .. " + workspace", hl.dsp._1(), { repeating = true })
-- TODO: manual review on line 77 — no mapping for dispatcher "+1"
-- hl.bind(kbNextWs .. " + workspace", hl.dsp._1(), { repeating = true })
hl.bind(mainMod .. " + Page_Up", hl.dsp.focus({ workspace = -1 }), { repeating = true })
hl.bind(mainMod .. " + Page_Down", hl.dsp.focus({ workspace = "+1" }), { repeating = true })
-- Go to workspace group -1/+1
hl.bind("Ctrl+$mainMod + mouse_down", hl.dsp.focus({ workspace = -10 }))
hl.bind("Ctrl+$mainMod + mouse_up", hl.dsp.focus({ workspace = "+10" }))
-- Toggle special workspace
--bind = $kbToggleSpecialWs, exec, caelestia toggle specialws

-- Move window to workspace #
hl.bind(kbMoveWinToWs .. " + 1", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 1"))
hl.bind(kbMoveWinToWs .. " + 2", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 2"))
hl.bind(kbMoveWinToWs .. " + 3", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 3"))
hl.bind(kbMoveWinToWs .. " + 4", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 4"))
hl.bind(kbMoveWinToWs .. " + 5", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 5"))
hl.bind(kbMoveWinToWs .. " + 6", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 6"))
hl.bind(kbMoveWinToWs .. " + 7", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 7"))
hl.bind(kbMoveWinToWs .. " + 8", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 8"))
hl.bind(kbMoveWinToWs .. " + 9", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 9"))
hl.bind(kbMoveWinToWs .. " + 0", hl.dsp.exec_cmd(wsaction .. " movetoworkspace 10"))
-- Move window to workspace group #
hl.bind(kbMoveWinToWsGroup .. " + 1", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 1"))
hl.bind(kbMoveWinToWsGroup .. " + 2", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 2"))
hl.bind(kbMoveWinToWsGroup .. " + 3", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 3"))
hl.bind(kbMoveWinToWsGroup .. " + 4", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 4"))
hl.bind(kbMoveWinToWsGroup .. " + 5", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 5"))
hl.bind(kbMoveWinToWsGroup .. " + 6", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 6"))
hl.bind(kbMoveWinToWsGroup .. " + 7", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 7"))
hl.bind(kbMoveWinToWsGroup .. " + 8", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 8"))
hl.bind(kbMoveWinToWsGroup .. " + 9", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 9"))
hl.bind(kbMoveWinToWsGroup .. " + 0", hl.dsp.exec_cmd(wsaction .. " -g movetoworkspace 10"))
-- Move window to workspace -1/+1
hl.bind("$mainMod+Alt + Page_Up", hl.dsp.window.move({ workspace = -1 }), { repeating = true })
hl.bind("$mainMod+Alt + Page_Down", hl.dsp.window.move({ workspace = "+1" }), { repeating = true })
hl.bind("$mainMod+Alt + mouse_down", hl.dsp.window.move({ workspace = -1 }))
hl.bind("$mainMod+Alt + mouse_up", hl.dsp.window.move({ workspace = "+1" }))
hl.bind("Ctrl+$mainMod+Shift + right", hl.dsp.window.move({ workspace = "+1" }), { repeating = true })
hl.bind("Ctrl+$mainMod+Shift + left", hl.dsp.window.move({ workspace = -1 }), { repeating = true })
-- Move window to/from special workspace
--bind = Ctrl+$mainMod+Shift, up, movetoworkspace, special:special
--bind = Ctrl+$mainMod+Shift, down, movetoworkspace, e+0
--bind = $mainMod+Alt, S, movetoworkspace, special:special

-- Window groups
-- TODO: manual review — malformed bind on line 121: $kbWindowGroupCycleNext, cyclenext
-- TODO: manual review on line 122 — no mapping for dispatcher "prev"
-- hl.bind(kbWindowGroupCyclePrev .. " + cyclenext", hl.dsp.prev(), { repeating = true })
hl.bind("Ctrl+Alt + Tab", hl.dsp.group.next(), { repeating = true })
hl.bind("Ctrl+Shift+Alt + Tab", hl.dsp.group.prev(), { repeating = true })
-- TODO: manual review — malformed bind on line 125: $kbToggleGroup, togglegroup
-- TODO: manual review — malformed bind on line 126: $kbUngroup, moveoutofgroup
--bind = $mainMod+Shift, Comma, lockactivegroup, toggle

-- Window actions
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind("$mainMod+Shift + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("$mainMod+Shift + L", hl.dsp.window.move({ direction = "r" }))
hl.bind("$mainMod+Shift + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("$mainMod+Shift + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + Minus", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(w.size.x * -10 / 100), y = 0, relative = true })) end, { repeating = true })
hl.bind(mainMod .. " + Equal", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(w.size.x * 10 / 100), y = 0, relative = true })) end, { repeating = true })
hl.bind("$mainMod+Shift + Minus", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = 0, y = math.floor(w.size.y * -10 / 100), relative = true })) end, { repeating = true })
hl.bind("$mainMod+Shift + Equal", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = 0, y = math.floor(w.size.y * 10 / 100), relative = true })) end, { repeating = true })
hl.bind("$mainMod+Alt+Shift + left", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(w.size.x * -10 / 100), y = 0, relative = true })) end, { repeating = true })
hl.bind("$mainMod+Alt+Shift + right", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(w.size.x * 10 / 100), y = 0, relative = true })) end, { repeating = true })
hl.bind("$mainMod+Alt+Shift + up", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = 0, y = math.floor(w.size.y * -10 / 100), relative = true })) end, { repeating = true })
hl.bind("$mainMod+Alt+Shift + down", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = 0, y = math.floor(w.size.y * 10 / 100), relative = true })) end, { repeating = true })
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
-- TODO: manual review — malformed bind on line 147: $kbMoveWindow, movewindow
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
-- TODO: manual review — malformed bind on line 149: $kbResizeWindow, resizewindow
hl.bind("Ctrl+$mainMod + Backslash", hl.dsp.window.center() --[[ legacy `1` arg (respect-reserved) has no typed equivalent in 0.55 ]])
hl.bind("Ctrl+$mainMod+Alt + Backslash", function() local m = hl.get_active_monitor(); if not m then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(m.width * 55 / 100), y = math.floor(m.height * 70 / 100) })) end)
hl.bind("Ctrl+$mainMod+Alt + Backslash", hl.dsp.window.center() --[[ legacy `1` arg (respect-reserved) has no typed equivalent in 0.55 ]])
-- TODO: manual review on line 153 — no mapping for dispatcher "caelestia resizer pip"
-- hl.bind(kbWindowPip .. " + exec", hl.dsp.caelestia_resizer_pip())
-- TODO: manual review — malformed bind on line 154: $kbPinWindow, pin
-- TODO: manual review on line 155 — no mapping for dispatcher "0"
-- hl.bind(kbWindowFullscreen .. " + fullscreen", hl.dsp.0())
--bind = $kbWindowBorderedFullscreen, fullscreen, 1  # Fullscreen with borders
-- TODO: manual review on line 157 — no mapping for dispatcher ""
-- hl.bind(kbToggleWindowFloating .. " + togglefloating", hl.dsp.no_op())
-- TODO: manual review on line 158 — no mapping for dispatcher ""
-- hl.bind(kbCloseWindow .. " + killactive", hl.dsp.no_op())

-- Special workspace toggles
-- TODO: manual review on line 161 — no mapping for dispatcher "caelestia toggle sysmon"
-- hl.bind(kbSystemMonitor .. " + exec", hl.dsp.caelestia_toggle_sysmon())
-- TODO: manual review on line 162 — no mapping for dispatcher "caelestia toggle music"
-- hl.bind(kbMusic .. " + exec", hl.dsp.caelestia_toggle_music())
-- TODO: manual review on line 163 — no mapping for dispatcher "caelestia toggle communication"
-- hl.bind(kbCommunication .. " + exec", hl.dsp.caelestia_toggle_communication())
-- TODO: manual review on line 164 — no mapping for dispatcher "caelestia toggle todo"
-- hl.bind(kbTodo .. " + exec", hl.dsp.caelestia_toggle_todo())

-- Apps
-- TODO: manual review on line 167 — no mapping for dispatcher "app2unit -- $terminal"
-- hl.bind(kbTerminal .. " + exec", hl.dsp.app2unit_____terminal())
-- TODO: manual review on line 168 — no mapping for dispatcher "app2unit -- $browser"
-- hl.bind(kbBrowser .. " + exec", hl.dsp.app2unit_____browser())
-- TODO: manual review on line 169 — no mapping for dispatcher "app2unit -- $editor"
-- hl.bind(kbEditor .. " + exec", hl.dsp.app2unit_____editor())
--bind = $mainMod, G, exec, app2unit -- github-desktop
-- TODO: manual review on line 171 — no mapping for dispatcher "app2unit -- $fileExplorer"
-- hl.bind(kbFileExplorer .. " + exec", hl.dsp.app2unit_____fileExplorer())
--bind = $mainMod+Alt, E, exec, app2unit -- nemo
hl.bind("Ctrl+Alt + Escape", hl.dsp.exec_cmd("app2unit -- qps"))
hl.bind("Ctrl+Alt + V", hl.dsp.exec_cmd("app2unit -- pavucontrol"))

-- Utilities
hl.bind("Print", hl.dsp.exec_cmd("caelestia screenshot"), { locked = true })
hl.bind(mainMod .. " + S", hl.dsp.global("caelestia:screenshotFreeze"))
hl.bind(mainMod .. " + + + SHIFT + S", hl.dsp.global("caelestia:screenshot"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("caelestia record -s"))
hl.bind("Ctrl+Alt + R", hl.dsp.exec_cmd("caelestia record"))
hl.bind("$mainMod+Shift + R", hl.dsp.exec_cmd("caelestia record -r"))
hl.bind("$mainMod+Shift + C", hl.dsp.exec_cmd("hyprpicker -a"))

-- Volume
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("$mainMod+Shift + M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ $volumeStep%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%-"), { locked = true, repeating = true })

-- Sleep
hl.bind("Super+Shift + L", hl.dsp.exec_cmd("systemctl suspend-then-hibernate"), { locked = true })

-- Clipboard and emoji picker
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard"))
hl.bind(mainMod .. " + + + SHIFT + V", hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard -d"))
hl.bind(mainMod .. " + Period", hl.dsp.exec_cmd("pkill fuzzel || caelestia emoji -p"))
-- These come from hyde, may not work on a new caelestia install
--bindd = $mainMod, comma, $d emoji  picker , exec, pkill -x rofi || $scrPath/emoji-picker.sh # launch emoji picker
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("pkill -x rofi || $scrPath/glyph-picker.sh"), { description = "$d glyph picker" })
hl.bind("Ctrl+Shift+Alt + V", hl.dsp.exec_cmd("sleep 0.5s && ydotool type -d 1 \"$(cliphist list | head -1 | cliphist decode)\""), { locked = true })

-- Testing
hl.bind(mainMod .. " + f12", hl.dsp.exec_cmd("notify-send -u low -i dialog-information-symbolic 'Test notification' \"Here's a really long message to test truncation and wrapping\\nYou can middle click or flick this notification to dismiss it!\" -a 'Shell' -A \"Test1=I got it!\" -A \"Test2=Another action\""), { locked = true })

hl.on("config.reloaded", function()
    hl.exec_cmd("hyprctl dispatch submap global")
end)

